### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by MaoYafei** [srbehera11/stag-cns#1]
Dear All,

I tried to compile the Stag-cns but it did not work. look likes below:

 g++ -o stagCNS stagCNS.cpp
> stagCNS.cpp: In function ‘int main(int, char**)’:
> stagCNS.cpp:3068:8: error: redeclaration of ‘int i’
>     int i = 0;
>         ^
> stagCNS.cpp:3011:17: error: ‘int i’ previously declared here
>          for(int i = 0; i < numKmerLens; i++)
>                  ^

Then, I remove 'int' on line 3068 in stagCNS.cpp file,

before:

>             int cnt2 = mem_strings.size();
>                         string  *MEM = new string[cnt2];
>                         int i = 0;
after:

>             int cnt2 = mem_strings.size();
>                         string  *MEM = new string[cnt2];
>                         i = 0; 

And then, I got warnings like below but it seems compiling successfully. 

> 
> stagCNS.cpp: In function ‘int main(int, char**)’:
> stagCNS.cpp:3318:4: warning: name lookup of ‘i’ changed [enabled by default]
>     i = 0;
>     ^
> stagCNS.cpp:3011:17: warning:   matches this ‘i’ under ISO standard rules [enabled by default]
>          for(int i = 0; i < numKmerLens; i++)
>                  ^
> stagCNS.cpp:3076:21: warning:   matches this ‘i’ under old rules [enabled by default]
>              for(int i=0; i<cnt1; i++) check[i] = 0;

May I have few questions about the compiling?
(1)did I compile successfully with the remove action?
(2)does the remove action have effect on the Stag-cns's computation results?

Thanks for your working on this software and looking forward to your kind reply.

Best, 
Yafei

**Comment by srbehera11** [comment]
Hi Yafei,
Thanks for trying the code. Yes, you did compile successfully. You can ignore the warnings. If you are using C++11 compiler, you can add -std=c++11 or -std=c++0x. 

Please let me know if you have any more issues.

**Comment by MaoYafei** [comment]
Hi Sairam,

Thanks for your reply.
I tried to run the test data and it worked. But the the browser visualization can not work (XDAT works).

More, I still have some confusions in this pipeline, may I have your help?

(1). You mentioned at beginning "finding conserved regions in grass genomes" in README.md, then does it also fit to other non-plants data?

(2). In my understanding, this pipeline is only suitable to carry out CNS in promoters regions, but it cannot find the CNS in intro or 3'UTR regions. Right?

(3). Do you mind describing more details on input and output files?

Thanks again. 

Best, 
Yafei

**Comment by sbdk82** [comment]
Hi Yafei, 
I would love to help you. This will work for non-plant data also. It can find the CNS in 3' UTR region. I will check the code again and fix the issues asap. 

Thanks,
Sairam

**Comment by srbehera11** [comment]
Hi Yafei,
I would love to help you. This will work for non-plant data also. It can find the CNS in 3' UTR region. I will check the code again and fix the issues asap.

-Sairam

**Comment by MaoYafei** [comment]
Hi Sairam,

Thanks so much.

Yafei
